#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetraERP.Shared.Datasources
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Petra_ERP")]
	public partial class ERPDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertERP_Application(ERP_Application instance);
    partial void UpdateERP_Application(ERP_Application instance);
    partial void DeleteERP_Application(ERP_Application instance);
    partial void InsertERP_Department(ERP_Department instance);
    partial void UpdateERP_Department(ERP_Department instance);
    partial void DeleteERP_Department(ERP_Department instance);
    partial void InsertERP_User(ERP_User instance);
    partial void UpdateERP_User(ERP_User instance);
    partial void DeleteERP_User(ERP_User instance);
    partial void InsertERP_Setting(ERP_Setting instance);
    partial void UpdateERP_Setting(ERP_Setting instance);
    partial void DeleteERP_Setting(ERP_Setting instance);
    partial void InsertERP_Users_Role(ERP_Users_Role instance);
    partial void UpdateERP_Users_Role(ERP_Users_Role instance);
    partial void DeleteERP_Users_Role(ERP_Users_Role instance);
    partial void InsertERP_Role(ERP_Role instance);
    partial void UpdateERP_Role(ERP_Role instance);
    partial void DeleteERP_Role(ERP_Role instance);
    partial void InsertERP_Notification(ERP_Notification instance);
    partial void UpdateERP_Notification(ERP_Notification instance);
    partial void DeleteERP_Notification(ERP_Notification instance);
    #endregion
		
		public ERPDBDataContext() : 
				base(global::PetraERP.Shared.Properties.Settings.Default.Petra_ERPConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ERPDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ERPDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ERPDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ERPDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ERP_Application> ERP_Applications
		{
			get
			{
				return this.GetTable<ERP_Application>();
			}
		}
		
		public System.Data.Linq.Table<ERP_Department> ERP_Departments
		{
			get
			{
				return this.GetTable<ERP_Department>();
			}
		}
		
		public System.Data.Linq.Table<ERP_User> ERP_Users
		{
			get
			{
				return this.GetTable<ERP_User>();
			}
		}
		
		public System.Data.Linq.Table<ERP_Setting> ERP_Settings
		{
			get
			{
				return this.GetTable<ERP_Setting>();
			}
		}
		
		public System.Data.Linq.Table<ERP_Users_Role> ERP_Users_Roles
		{
			get
			{
				return this.GetTable<ERP_Users_Role>();
			}
		}
		
		public System.Data.Linq.Table<ERP_Role> ERP_Roles
		{
			get
			{
				return this.GetTable<ERP_Role>();
			}
		}
		
		public System.Data.Linq.Table<ERP_Notification> ERP_Notifications
		{
			get
			{
				return this.GetTable<ERP_Notification>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ERP_Applications")]
	public partial class ERP_Application : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _description;
		
		private System.Nullable<System.DateTime> _created_at;
		
		private System.Nullable<System.DateTime> _updated_at;
		
		private EntitySet<ERP_Role> _ERP_Roles;
		
		private EntitySet<ERP_Notification> _ERP_Notifications;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Oncreated_atChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_atChanged();
    partial void Onupdated_atChanging(System.Nullable<System.DateTime> value);
    partial void Onupdated_atChanged();
    #endregion
		
		public ERP_Application()
		{
			this._ERP_Roles = new EntitySet<ERP_Role>(new Action<ERP_Role>(this.attach_ERP_Roles), new Action<ERP_Role>(this.detach_ERP_Roles));
			this._ERP_Notifications = new EntitySet<ERP_Notification>(new Action<ERP_Notification>(this.attach_ERP_Notifications), new Action<ERP_Notification>(this.detach_ERP_Notifications));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime2")]
		public System.Nullable<System.DateTime> created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="DateTime2")]
		public System.Nullable<System.DateTime> updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ERP_Application_ERP_Role", Storage="_ERP_Roles", ThisKey="id", OtherKey="application_id")]
		public EntitySet<ERP_Role> ERP_Roles
		{
			get
			{
				return this._ERP_Roles;
			}
			set
			{
				this._ERP_Roles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ERP_Application_ERP_Notification", Storage="_ERP_Notifications", ThisKey="id", OtherKey="application_id")]
		public EntitySet<ERP_Notification> ERP_Notifications
		{
			get
			{
				return this._ERP_Notifications;
			}
			set
			{
				this._ERP_Notifications.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ERP_Roles(ERP_Role entity)
		{
			this.SendPropertyChanging();
			entity.ERP_Application = this;
		}
		
		private void detach_ERP_Roles(ERP_Role entity)
		{
			this.SendPropertyChanging();
			entity.ERP_Application = null;
		}
		
		private void attach_ERP_Notifications(ERP_Notification entity)
		{
			this.SendPropertyChanging();
			entity.ERP_Application = this;
		}
		
		private void detach_ERP_Notifications(ERP_Notification entity)
		{
			this.SendPropertyChanging();
			entity.ERP_Application = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ERP_Departments")]
	public partial class ERP_Department : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _description;
		
		private int _modified_by;
		
		private System.DateTime _created_at;
		
		private System.DateTime _updated_at;
		
		private EntitySet<ERP_User> _ERP_Users;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Onmodified_byChanging(int value);
    partial void Onmodified_byChanged();
    partial void Oncreated_atChanging(System.DateTime value);
    partial void Oncreated_atChanged();
    partial void Onupdated_atChanging(System.DateTime value);
    partial void Onupdated_atChanged();
    #endregion
		
		public ERP_Department()
		{
			this._ERP_Users = new EntitySet<ERP_User>(new Action<ERP_User>(this.attach_ERP_Users), new Action<ERP_User>(this.detach_ERP_Users));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_by", DbType="Int NOT NULL")]
		public int modified_by
		{
			get
			{
				return this._modified_by;
			}
			set
			{
				if ((this._modified_by != value))
				{
					this.Onmodified_byChanging(value);
					this.SendPropertyChanging();
					this._modified_by = value;
					this.SendPropertyChanged("modified_by");
					this.Onmodified_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime2 NOT NULL")]
		public System.DateTime created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="DateTime2 NOT NULL")]
		public System.DateTime updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ERP_Department_ERP_User", Storage="_ERP_Users", ThisKey="id", OtherKey="department_id")]
		public EntitySet<ERP_User> ERP_Users
		{
			get
			{
				return this._ERP_Users;
			}
			set
			{
				this._ERP_Users.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ERP_Users(ERP_User entity)
		{
			this.SendPropertyChanging();
			entity.ERP_Department = this;
		}
		
		private void detach_ERP_Users(ERP_User entity)
		{
			this.SendPropertyChanging();
			entity.ERP_Department = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ERP_Users")]
	public partial class ERP_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _department_id;
		
		private string _username;
		
		private string _password;
		
		private string _first_name;
		
		private string _middle_name;
		
		private string _last_name;
		
		private bool _status;
		
		private string _theme;
		
		private string _accent;
		
		private bool _first_login;
		
		private System.DateTime _last_login;
		
		private bool _logged_in;
		
		private int _modified_by;
		
		private System.DateTime _created_at;
		
		private System.DateTime _updated_at;
		
		private EntitySet<ERP_Users_Role> _ERP_Users_Roles;
		
		private EntityRef<ERP_Department> _ERP_Department;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Ondepartment_idChanging(int value);
    partial void Ondepartment_idChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Onfirst_nameChanging(string value);
    partial void Onfirst_nameChanged();
    partial void Onmiddle_nameChanging(string value);
    partial void Onmiddle_nameChanged();
    partial void Onlast_nameChanging(string value);
    partial void Onlast_nameChanged();
    partial void OnstatusChanging(bool value);
    partial void OnstatusChanged();
    partial void OnthemeChanging(string value);
    partial void OnthemeChanged();
    partial void OnaccentChanging(string value);
    partial void OnaccentChanged();
    partial void Onfirst_loginChanging(bool value);
    partial void Onfirst_loginChanged();
    partial void Onlast_loginChanging(System.DateTime value);
    partial void Onlast_loginChanged();
    partial void Onlogged_inChanging(bool value);
    partial void Onlogged_inChanged();
    partial void Onmodified_byChanging(int value);
    partial void Onmodified_byChanged();
    partial void Oncreated_atChanging(System.DateTime value);
    partial void Oncreated_atChanged();
    partial void Onupdated_atChanging(System.DateTime value);
    partial void Onupdated_atChanged();
    #endregion
		
		public ERP_User()
		{
			this._ERP_Users_Roles = new EntitySet<ERP_Users_Role>(new Action<ERP_Users_Role>(this.attach_ERP_Users_Roles), new Action<ERP_Users_Role>(this.detach_ERP_Users_Roles));
			this._ERP_Department = default(EntityRef<ERP_Department>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department_id", DbType="Int NOT NULL")]
		public int department_id
		{
			get
			{
				return this._department_id;
			}
			set
			{
				if ((this._department_id != value))
				{
					if (this._ERP_Department.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondepartment_idChanging(value);
					this.SendPropertyChanging();
					this._department_id = value;
					this.SendPropertyChanged("department_id");
					this.Ondepartment_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="Char(60) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string first_name
		{
			get
			{
				return this._first_name;
			}
			set
			{
				if ((this._first_name != value))
				{
					this.Onfirst_nameChanging(value);
					this.SendPropertyChanging();
					this._first_name = value;
					this.SendPropertyChanged("first_name");
					this.Onfirst_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_middle_name", DbType="NVarChar(50)")]
		public string middle_name
		{
			get
			{
				return this._middle_name;
			}
			set
			{
				if ((this._middle_name != value))
				{
					this.Onmiddle_nameChanging(value);
					this.SendPropertyChanging();
					this._middle_name = value;
					this.SendPropertyChanged("middle_name");
					this.Onmiddle_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string last_name
		{
			get
			{
				return this._last_name;
			}
			set
			{
				if ((this._last_name != value))
				{
					this.Onlast_nameChanging(value);
					this.SendPropertyChanging();
					this._last_name = value;
					this.SendPropertyChanged("last_name");
					this.Onlast_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit NOT NULL")]
		public bool status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_theme", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string theme
		{
			get
			{
				return this._theme;
			}
			set
			{
				if ((this._theme != value))
				{
					this.OnthemeChanging(value);
					this.SendPropertyChanging();
					this._theme = value;
					this.SendPropertyChanged("theme");
					this.OnthemeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accent", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string accent
		{
			get
			{
				return this._accent;
			}
			set
			{
				if ((this._accent != value))
				{
					this.OnaccentChanging(value);
					this.SendPropertyChanging();
					this._accent = value;
					this.SendPropertyChanged("accent");
					this.OnaccentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_login", DbType="Bit NOT NULL")]
		public bool first_login
		{
			get
			{
				return this._first_login;
			}
			set
			{
				if ((this._first_login != value))
				{
					this.Onfirst_loginChanging(value);
					this.SendPropertyChanging();
					this._first_login = value;
					this.SendPropertyChanged("first_login");
					this.Onfirst_loginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_login", DbType="DateTime2 NOT NULL")]
		public System.DateTime last_login
		{
			get
			{
				return this._last_login;
			}
			set
			{
				if ((this._last_login != value))
				{
					this.Onlast_loginChanging(value);
					this.SendPropertyChanging();
					this._last_login = value;
					this.SendPropertyChanged("last_login");
					this.Onlast_loginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logged_in", DbType="Bit NOT NULL")]
		public bool logged_in
		{
			get
			{
				return this._logged_in;
			}
			set
			{
				if ((this._logged_in != value))
				{
					this.Onlogged_inChanging(value);
					this.SendPropertyChanging();
					this._logged_in = value;
					this.SendPropertyChanged("logged_in");
					this.Onlogged_inChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_by", DbType="Int NOT NULL")]
		public int modified_by
		{
			get
			{
				return this._modified_by;
			}
			set
			{
				if ((this._modified_by != value))
				{
					this.Onmodified_byChanging(value);
					this.SendPropertyChanging();
					this._modified_by = value;
					this.SendPropertyChanged("modified_by");
					this.Onmodified_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime2 NOT NULL")]
		public System.DateTime created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="DateTime2 NOT NULL")]
		public System.DateTime updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ERP_User_ERP_Users_Role", Storage="_ERP_Users_Roles", ThisKey="id", OtherKey="user_id")]
		public EntitySet<ERP_Users_Role> ERP_Users_Roles
		{
			get
			{
				return this._ERP_Users_Roles;
			}
			set
			{
				this._ERP_Users_Roles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ERP_Department_ERP_User", Storage="_ERP_Department", ThisKey="department_id", OtherKey="id", IsForeignKey=true)]
		public ERP_Department ERP_Department
		{
			get
			{
				return this._ERP_Department.Entity;
			}
			set
			{
				ERP_Department previousValue = this._ERP_Department.Entity;
				if (((previousValue != value) 
							|| (this._ERP_Department.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ERP_Department.Entity = null;
						previousValue.ERP_Users.Remove(this);
					}
					this._ERP_Department.Entity = value;
					if ((value != null))
					{
						value.ERP_Users.Add(this);
						this._department_id = value.id;
					}
					else
					{
						this._department_id = default(int);
					}
					this.SendPropertyChanged("ERP_Department");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ERP_Users_Roles(ERP_Users_Role entity)
		{
			this.SendPropertyChanging();
			entity.ERP_User = this;
		}
		
		private void detach_ERP_Users_Roles(ERP_Users_Role entity)
		{
			this.SendPropertyChanging();
			entity.ERP_User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ERP_Settings")]
	public partial class ERP_Setting : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _setting;
		
		private string _value;
		
		private int _modified_by;
		
		private System.DateTime _created_at;
		
		private System.DateTime _updated_at;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnsettingChanging(string value);
    partial void OnsettingChanged();
    partial void OnvalueChanging(string value);
    partial void OnvalueChanged();
    partial void Onmodified_byChanging(int value);
    partial void Onmodified_byChanged();
    partial void Oncreated_atChanging(System.DateTime value);
    partial void Oncreated_atChanged();
    partial void Onupdated_atChanging(System.DateTime value);
    partial void Onupdated_atChanged();
    #endregion
		
		public ERP_Setting()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_setting", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string setting
		{
			get
			{
				return this._setting;
			}
			set
			{
				if ((this._setting != value))
				{
					this.OnsettingChanging(value);
					this.SendPropertyChanging();
					this._setting = value;
					this.SendPropertyChanged("setting");
					this.OnsettingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this.OnvalueChanging(value);
					this.SendPropertyChanging();
					this._value = value;
					this.SendPropertyChanged("value");
					this.OnvalueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_by", DbType="Int NOT NULL")]
		public int modified_by
		{
			get
			{
				return this._modified_by;
			}
			set
			{
				if ((this._modified_by != value))
				{
					this.Onmodified_byChanging(value);
					this.SendPropertyChanging();
					this._modified_by = value;
					this.SendPropertyChanged("modified_by");
					this.Onmodified_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime2 NOT NULL")]
		public System.DateTime created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="DateTime2 NOT NULL")]
		public System.DateTime updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ERP_Users_Roles")]
	public partial class ERP_Users_Role : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _user_id;
		
		private int _role_id;
		
		private int _modified_by;
		
		private System.DateTime _created_at;
		
		private System.DateTime _updated_at;
		
		private EntityRef<ERP_User> _ERP_User;
		
		private EntityRef<ERP_Role> _ERP_Role;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onrole_idChanging(int value);
    partial void Onrole_idChanged();
    partial void Onmodified_byChanging(int value);
    partial void Onmodified_byChanged();
    partial void Oncreated_atChanging(System.DateTime value);
    partial void Oncreated_atChanged();
    partial void Onupdated_atChanging(System.DateTime value);
    partial void Onupdated_atChanged();
    #endregion
		
		public ERP_Users_Role()
		{
			this._ERP_User = default(EntityRef<ERP_User>);
			this._ERP_Role = default(EntityRef<ERP_Role>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL")]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					if (this._ERP_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role_id", DbType="Int NOT NULL")]
		public int role_id
		{
			get
			{
				return this._role_id;
			}
			set
			{
				if ((this._role_id != value))
				{
					if (this._ERP_Role.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onrole_idChanging(value);
					this.SendPropertyChanging();
					this._role_id = value;
					this.SendPropertyChanged("role_id");
					this.Onrole_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_by", DbType="Int NOT NULL")]
		public int modified_by
		{
			get
			{
				return this._modified_by;
			}
			set
			{
				if ((this._modified_by != value))
				{
					this.Onmodified_byChanging(value);
					this.SendPropertyChanging();
					this._modified_by = value;
					this.SendPropertyChanged("modified_by");
					this.Onmodified_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime2 NOT NULL")]
		public System.DateTime created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="DateTime2 NOT NULL")]
		public System.DateTime updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ERP_User_ERP_Users_Role", Storage="_ERP_User", ThisKey="user_id", OtherKey="id", IsForeignKey=true)]
		public ERP_User ERP_User
		{
			get
			{
				return this._ERP_User.Entity;
			}
			set
			{
				ERP_User previousValue = this._ERP_User.Entity;
				if (((previousValue != value) 
							|| (this._ERP_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ERP_User.Entity = null;
						previousValue.ERP_Users_Roles.Remove(this);
					}
					this._ERP_User.Entity = value;
					if ((value != null))
					{
						value.ERP_Users_Roles.Add(this);
						this._user_id = value.id;
					}
					else
					{
						this._user_id = default(int);
					}
					this.SendPropertyChanged("ERP_User");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ERP_Role_ERP_Users_Role", Storage="_ERP_Role", ThisKey="role_id", OtherKey="id", IsForeignKey=true)]
		public ERP_Role ERP_Role
		{
			get
			{
				return this._ERP_Role.Entity;
			}
			set
			{
				ERP_Role previousValue = this._ERP_Role.Entity;
				if (((previousValue != value) 
							|| (this._ERP_Role.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ERP_Role.Entity = null;
						previousValue.ERP_Users_Roles.Remove(this);
					}
					this._ERP_Role.Entity = value;
					if ((value != null))
					{
						value.ERP_Users_Roles.Add(this);
						this._role_id = value.id;
					}
					else
					{
						this._role_id = default(int);
					}
					this.SendPropertyChanged("ERP_Role");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ERP_Roles")]
	public partial class ERP_Role : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _application_id;
		
		private string _role;
		
		private string _description;
		
		private int _modified_by;
		
		private System.Nullable<System.DateTime> _created_at;
		
		private System.Nullable<System.DateTime> _updated_at;
		
		private EntitySet<ERP_Users_Role> _ERP_Users_Roles;
		
		private EntityRef<ERP_Application> _ERP_Application;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onapplication_idChanging(int value);
    partial void Onapplication_idChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Onmodified_byChanging(int value);
    partial void Onmodified_byChanged();
    partial void Oncreated_atChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_atChanged();
    partial void Onupdated_atChanging(System.Nullable<System.DateTime> value);
    partial void Onupdated_atChanged();
    #endregion
		
		public ERP_Role()
		{
			this._ERP_Users_Roles = new EntitySet<ERP_Users_Role>(new Action<ERP_Users_Role>(this.attach_ERP_Users_Roles), new Action<ERP_Users_Role>(this.detach_ERP_Users_Roles));
			this._ERP_Application = default(EntityRef<ERP_Application>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_application_id", DbType="Int NOT NULL")]
		public int application_id
		{
			get
			{
				return this._application_id;
			}
			set
			{
				if ((this._application_id != value))
				{
					if (this._ERP_Application.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onapplication_idChanging(value);
					this.SendPropertyChanging();
					this._application_id = value;
					this.SendPropertyChanged("application_id");
					this.Onapplication_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_by", DbType="Int NOT NULL")]
		public int modified_by
		{
			get
			{
				return this._modified_by;
			}
			set
			{
				if ((this._modified_by != value))
				{
					this.Onmodified_byChanging(value);
					this.SendPropertyChanging();
					this._modified_by = value;
					this.SendPropertyChanged("modified_by");
					this.Onmodified_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime2")]
		public System.Nullable<System.DateTime> created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="DateTime2")]
		public System.Nullable<System.DateTime> updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ERP_Role_ERP_Users_Role", Storage="_ERP_Users_Roles", ThisKey="id", OtherKey="role_id")]
		public EntitySet<ERP_Users_Role> ERP_Users_Roles
		{
			get
			{
				return this._ERP_Users_Roles;
			}
			set
			{
				this._ERP_Users_Roles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ERP_Application_ERP_Role", Storage="_ERP_Application", ThisKey="application_id", OtherKey="id", IsForeignKey=true)]
		public ERP_Application ERP_Application
		{
			get
			{
				return this._ERP_Application.Entity;
			}
			set
			{
				ERP_Application previousValue = this._ERP_Application.Entity;
				if (((previousValue != value) 
							|| (this._ERP_Application.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ERP_Application.Entity = null;
						previousValue.ERP_Roles.Remove(this);
					}
					this._ERP_Application.Entity = value;
					if ((value != null))
					{
						value.ERP_Roles.Add(this);
						this._application_id = value.id;
					}
					else
					{
						this._application_id = default(int);
					}
					this.SendPropertyChanged("ERP_Application");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ERP_Users_Roles(ERP_Users_Role entity)
		{
			this.SendPropertyChanging();
			entity.ERP_Role = this;
		}
		
		private void detach_ERP_Users_Roles(ERP_Users_Role entity)
		{
			this.SendPropertyChanging();
			entity.ERP_Role = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ERP_Notifications")]
	public partial class ERP_Notification : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _application_id;
		
		private int _to_user_id;
		
		private int _from_user_id;
		
		private string _notification_type;
		
		private string _job_type;
		
		private int _job_id;
		
		private System.DateTime _last_sent;
		
		private int _times_sent;
		
		private string _status;
		
		private int _modified_by;
		
		private System.DateTime _created_at;
		
		private System.DateTime _updated_at;
		
		private EntityRef<ERP_Application> _ERP_Application;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onapplication_idChanging(int value);
    partial void Onapplication_idChanged();
    partial void Onto_user_idChanging(int value);
    partial void Onto_user_idChanged();
    partial void Onfrom_user_idChanging(int value);
    partial void Onfrom_user_idChanged();
    partial void Onnotification_typeChanging(string value);
    partial void Onnotification_typeChanged();
    partial void Onjob_typeChanging(string value);
    partial void Onjob_typeChanged();
    partial void Onjob_idChanging(int value);
    partial void Onjob_idChanged();
    partial void Onlast_sentChanging(System.DateTime value);
    partial void Onlast_sentChanged();
    partial void Ontimes_sentChanging(int value);
    partial void Ontimes_sentChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void Onmodified_byChanging(int value);
    partial void Onmodified_byChanged();
    partial void Oncreated_atChanging(System.DateTime value);
    partial void Oncreated_atChanged();
    partial void Onupdated_atChanging(System.DateTime value);
    partial void Onupdated_atChanged();
    #endregion
		
		public ERP_Notification()
		{
			this._ERP_Application = default(EntityRef<ERP_Application>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_application_id", DbType="Int NOT NULL")]
		public int application_id
		{
			get
			{
				return this._application_id;
			}
			set
			{
				if ((this._application_id != value))
				{
					if (this._ERP_Application.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onapplication_idChanging(value);
					this.SendPropertyChanging();
					this._application_id = value;
					this.SendPropertyChanged("application_id");
					this.Onapplication_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_to_user_id", DbType="Int NOT NULL")]
		public int to_user_id
		{
			get
			{
				return this._to_user_id;
			}
			set
			{
				if ((this._to_user_id != value))
				{
					this.Onto_user_idChanging(value);
					this.SendPropertyChanging();
					this._to_user_id = value;
					this.SendPropertyChanged("to_user_id");
					this.Onto_user_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_from_user_id", DbType="Int NOT NULL")]
		public int from_user_id
		{
			get
			{
				return this._from_user_id;
			}
			set
			{
				if ((this._from_user_id != value))
				{
					this.Onfrom_user_idChanging(value);
					this.SendPropertyChanging();
					this._from_user_id = value;
					this.SendPropertyChanged("from_user_id");
					this.Onfrom_user_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notification_type", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string notification_type
		{
			get
			{
				return this._notification_type;
			}
			set
			{
				if ((this._notification_type != value))
				{
					this.Onnotification_typeChanging(value);
					this.SendPropertyChanging();
					this._notification_type = value;
					this.SendPropertyChanged("notification_type");
					this.Onnotification_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_type", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string job_type
		{
			get
			{
				return this._job_type;
			}
			set
			{
				if ((this._job_type != value))
				{
					this.Onjob_typeChanging(value);
					this.SendPropertyChanging();
					this._job_type = value;
					this.SendPropertyChanged("job_type");
					this.Onjob_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_id", DbType="Int NOT NULL")]
		public int job_id
		{
			get
			{
				return this._job_id;
			}
			set
			{
				if ((this._job_id != value))
				{
					this.Onjob_idChanging(value);
					this.SendPropertyChanging();
					this._job_id = value;
					this.SendPropertyChanged("job_id");
					this.Onjob_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_sent", DbType="DateTime2 NOT NULL")]
		public System.DateTime last_sent
		{
			get
			{
				return this._last_sent;
			}
			set
			{
				if ((this._last_sent != value))
				{
					this.Onlast_sentChanging(value);
					this.SendPropertyChanging();
					this._last_sent = value;
					this.SendPropertyChanged("last_sent");
					this.Onlast_sentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_times_sent", DbType="Int NOT NULL")]
		public int times_sent
		{
			get
			{
				return this._times_sent;
			}
			set
			{
				if ((this._times_sent != value))
				{
					this.Ontimes_sentChanging(value);
					this.SendPropertyChanging();
					this._times_sent = value;
					this.SendPropertyChanged("times_sent");
					this.Ontimes_sentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_by", DbType="Int NOT NULL")]
		public int modified_by
		{
			get
			{
				return this._modified_by;
			}
			set
			{
				if ((this._modified_by != value))
				{
					this.Onmodified_byChanging(value);
					this.SendPropertyChanging();
					this._modified_by = value;
					this.SendPropertyChanged("modified_by");
					this.Onmodified_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime2 NOT NULL")]
		public System.DateTime created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="DateTime2 NOT NULL")]
		public System.DateTime updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ERP_Application_ERP_Notification", Storage="_ERP_Application", ThisKey="application_id", OtherKey="id", IsForeignKey=true)]
		public ERP_Application ERP_Application
		{
			get
			{
				return this._ERP_Application.Entity;
			}
			set
			{
				ERP_Application previousValue = this._ERP_Application.Entity;
				if (((previousValue != value) 
							|| (this._ERP_Application.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ERP_Application.Entity = null;
						previousValue.ERP_Notifications.Remove(this);
					}
					this._ERP_Application.Entity = value;
					if ((value != null))
					{
						value.ERP_Notifications.Add(this);
						this._application_id = value.id;
					}
					else
					{
						this._application_id = default(int);
					}
					this.SendPropertyChanged("ERP_Application");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
